package vo;

public class NoticeBoardVo {

}

/*CREATE TABLE NOTICE_BOARD(
		 NOTICE_IDX NUMBER(10),
		 NOTICE_TITLE VARCHAR2(200),
		 NOTICE_CONTENT VARCHAR(3000),
		 NOTICE_WRITER VARCHAR2(20),
		 NOTICE_DATE DATE,
		 NOTICE_HIT NUMBER(10),
		 NOTICE_AVAILABLE NUMBER(2),
		 CONSTRAINT NOTICE_NOTICE_ID_PK PRIMARY KEY (NOTICE_IDX)
		)*/