package vo;

public class OrderVo {

}

/*CREATE TABLE ORDERS(
		 ORDER_CODE VARCHAR2(20),
		 USER_ID_FK VARCHAR2(20),
		 PRODUCT_CODE_PK VARCHAR2(20),
		 ORDER_COUNT NUMBER(6),
		 BUYER_NAME VARCHAR2(20),
		 BUYER_ADDRESS VARCHAR2(200),
		 BUYER_PHONE NUMBER(15),
		 BUYER_EMAIL VARCHAR2(30),
		 RCPT_NAME VARCHAR2(20),
		 RCPT_ADDRESS VARCHAR2(200),
		 RCPT_PHONE NUMBER(15),
		 SHIP_MESSAGE VARCHAR2(100),
		 ORDER_AMOUNT NUMBER(10),
		 ORDER_STATE NUMBER(2),
		 ORDER_DATE DATE,
		 CONSTRAINT ORDERS_ORDER_ID_PK PRIMARY KEY (ORDER_CODE)
		)*/