package vo;

public class ProductsVo {

}

/*CREATE TABLE PRODUCTS(
		 PRODUCT_CODE VARCHAR2(20),
		 CATEGORY1_CODE_FK VARCHAR2(20),
		 PRODUCT_NAME VARCHAR2(60),
		 PRODUCT_COMPANY VARCHAR2(30),
		 PRICE_RETAIL NUMBER(10),
		 PRICE_SALE NUMBER(10),
		 PRODUCT_QNTY NUMBER(10),
		 PRODUCT_IMAGE1 VARCHAR2(50),
		 PRODUCT_IMAGE2 VARCHAR2(50),
		 PRODUCT_MESSAGE VARCHAR2(1000),
		 PRODUCT_DATE DATE,
		 CONSTRAINT PRODUCTS_PRODUCT_CODE_PK PRIMARY KEY (PRODUCT_CODE)
		)*/