package vo;

public class QnaBoardVo {

}

/*CREATE TABLE QNA_BOARD(
		 QNA_IDX NUMBER(10),
		 QNA_TITLE VARCHAR2(200),
		 QNA_CONTENT VARCHAR2(3000),
		 QNA_WRITER VARCHAR2(20),
		 QNA_DATE DATE,
		 QNA_HIT NUMBER(10),
		 QNA_AVAILABLE NUMBER(2),
		 QNA_GROUP NUMBER(10),
		 QNA_STEP NUMBER(10),
		 QNA_INDENT NUMBER(10),
		 CONSTRAINT QNA_QNA_ID_PK PRIMARY KEY (QNA_IDX)
		)*/