package vo;

public class UserVo {

}

/*CREATE TABLE USERS(
		 USER_ID VARCHAR2(20),
		 USER_PASSWORD VARCHAR2(20),
		 USER_NAME VARCHAR2(20),
		 USER_ADDRESS VARCHAR2(200),
		 USER_PHONE NUMBER(15),
		 USER_EMAIL VARCHAR2(30),
		 CONSTRAINT USERS_USER_ID_PK PRIMARY KEY (USER_ID)
		)*/